name: Deploy VuePress Documentation

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can adjust this to your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build VuePress site
      run: npm run docs:build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/.vuepress/dist  # Adjust this if your output directory is different